
# Copyright (C) 2009 Realtek Semiconductor Corp.
#
# Makefile for SDK Linux RTK Module
#

ifeq ($(SDK_CONFIG), $(wildcard $(SDK_CONFIG)))
include $(SDK_CONFIG)
endif

include $(SDK_BUILD)/Makefile.linux.user.rtnic


