##############################################################################################
## Top Makefile
##
##


MODULES    := sdk dal common
UNITTEST_SRC := $(ROOT_PATH)/app/unittest/src

include $(UNITTEST_SRC)/sdk/Makefile
include $(UNITTEST_SRC)/dal/Makefile
include $(UNITTEST_SRC)/common/Makefile

##subdir:
##	for i in $(MODULES); do\
##		include $$i/Makefile; \
##	done

