/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009-2016
 * All rights reserved.
 *
 * $Revision$
 * $Date$
 *
 * Purpose : chip table field declaration in the SDK.
 *
 * Feature : chip table field declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/maple/rtk_maple_table_struct.h>

#if defined(CONFIG_SDK_CHIP_FEATURE_TABLE_ACCESS)
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_IACL_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_11",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   560,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_10",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   544,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_9",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   528,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_8",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   512,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_7",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   496,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_6",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   480,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_5",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   464,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   448,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   432,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   416,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   400,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   384,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SPMMASK_FIX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   374,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SPN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   368,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MGNT_VLAN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   367,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "DMAC_HIT_SW",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   366,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NOT_FIRST_FRAG",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   365,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FRAME_TYPE_L4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   362,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FRAME_TYPE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   360,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OTAG_FMT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   359,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ITAG_FMT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   358,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OTAG_EXIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   357,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ITAG_EXIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   356,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FRAME_TYPE_L2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   354,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   352,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_11",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   336,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_10",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   320,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_9",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   304,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_8",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   288,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_7",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   272,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_6",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   256,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_5",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   240,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   224,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   208,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   192,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   176,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   160,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_SPMMASK_FIX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   150,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_SPN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   144,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_MGNT_VLAN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   143,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_DMAC_HIT_SW",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   142,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_NOT_FIRST_FRAG",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   141,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FRAME_TYPE_L4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   138,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FRAME_TYPE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   136,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_OTAG_FMT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   135,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ITAG_FMT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   134,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_OTAG_EXIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   133,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ITAG_EXIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   132,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FRAME_TYPE_L2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   130,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_TID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   128,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VALID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   127,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NOT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   126,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AND1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   125,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AND2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   124,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IVALID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   123,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AIF4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   96,
        /* len */   9,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AIF3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   80,
        /* len */   10,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AIF2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   14,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AIF1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   48,
        /* len */   14,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AIF0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "DROP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   14,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FWD_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   13,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OVID_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   12,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IVID_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   11,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FLT_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   10,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LOG_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   9,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "RMK_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   8,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "METER_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   7,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TAGST_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   6,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MIR_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   5,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NORPRI_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   4,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "CPUPRI_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   3,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OTPID_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   2,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ITPID_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   1,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SHAPER_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_CAM_IP_MC_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   86,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   85,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MC_PMSK_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   76,
        /* len */   9,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "GIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   12,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_CAM_IP_MC_SIP_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   86,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   85,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MC_PMSK_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   76,
        /* len */   9,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "GIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_CAM_MC_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   86,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   85,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MC_PMSK_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   76,
        /* len */   9,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   12,
        /* len */   48,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_CAM_UC_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   86,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   85,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATIC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   83,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AGE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   81,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SLP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   76,
        /* len */   5,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SA_BLK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   63,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "DA_BLK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   62,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SUSPEND",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   61,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEXT_HOP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   60,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   12,
        /* len */   48,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_IP_MC_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   86,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   85,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MC_PMSK_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   76,
        /* len */   9,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "GIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   12,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_IP_MC_SIP_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   86,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   85,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MC_PMSK_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   76,
        /* len */   9,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "GIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   32,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_MC_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   86,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   85,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MC_PMSK_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   76,
        /* len */   9,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   12,
        /* len */   48,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_NEXT_HOP_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   86,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   85,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATIC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   83,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AGE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   81,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SLP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   76,
        /* len */   5,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VLAN_TARGET",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   73,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ROUTE_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   9,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SA_BLK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   63,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "DA_BLK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   62,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SUSPEND",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   61,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEXT_HOP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   60,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   12,
        /* len */   48,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_NEXT_HOP_LEGACY_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   86,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   85,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "DPA",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   76,
        /* len */   5,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEXT_HOP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   60,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "GWMAC_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   25,
        /* len */   9,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "DVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   13,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   12,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_L2_UC_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   86,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   85,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATIC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   83,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AGE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   81,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SLP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   76,
        /* len */   5,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SA_BLK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   63,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "DA_BLK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   62,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SUSPEND",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   61,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEXT_HOP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   60,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   12,
        /* len */   48,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_LOG_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "CNTR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   64,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_MC_PMSK_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PMSK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   29,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_MSTI_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT28",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   56,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT27",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   54,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT26",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   52,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT25",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   50,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT24",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   48,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT23",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   46,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT22",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   44,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT21",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   42,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT20",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   40,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT19",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   38,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT18",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   36,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT17",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   34,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT16",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT15",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT14",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   28,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT13",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   26,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT12",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   24,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT11",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   22,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT10",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   20,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT9",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   18,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT8",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   16,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT7",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   14,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT6",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   12,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT5",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   10,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   8,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   6,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   4,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   2,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_ROUTING_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "GATEWAY_MAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   48,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_UNTAG_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PMSK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   29,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_VLAN_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MBR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   29,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_MSTI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   5,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "L2_HASH_KEY_UC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   4,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "L2_HASH_KEY_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   3,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VLAN_PROFILE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8380)
rtk_tableField_t RTL8380_VLAN_EGR_CNVT_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VALID1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   191,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ORGPRI1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   188,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ORG_VID1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   176,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ORG_VID_RNG_CHK1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   160,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ORGPRI1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   156,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ORG_VID1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   144,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ORG_VID_RNG_CHK1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   128,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PORT_ID1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   118,
        /* len */   5,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_PORT_ID1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   113,
        /* len */   5,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID_SHIFT1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   112,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEW_VID1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   100,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PRI_ASSIGN1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   99,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEW_PRI1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   96,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VALID0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   95,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ORGPRI0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   92,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ORG_VID0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   80,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ORG_VID_RNG_CHK0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ORGPRI0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   60,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ORG_VID0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   48,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ORG_VID_RNG_CHK0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PORT_ID0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   22,
        /* len */   5,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_PORT_ID0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   17,
        /* len */   5,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID_SHIFT0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   16,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEW_VID0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   4,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PRI_ASSIGN0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   3,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEW_PRI0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   3,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_TABLE_ACCESS */

