---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/14/24 6:04 PM
---

local tf = require "tf_module"

local sensor_module = {}

sensor_module.hwSensorEnum = {
    {"inputTamper", "TAMPER" },
    {"inputSensor1", "SENSOR1" },
    {"inputSensor2", "SENSOR2" },
    {"sensorTemperature", "SHT_TEMPERATURE" },
    {"sensorHumidity", "SHT_HUMIDITY" }
}

local jsonInfo  = {}

local function getUbusData()
    jsonInfo = tf.collectJsonTable("ubus call hw_sensor getStatus")
end

function sensor_module.getTemperature()
    getUbusData()
    return jsonInfo.hwSensors.sensorTemperature
end

function sensor_module.getHumidity()
    getUbusData()
    return jsonInfo.hwSensors.sensorHumidity
end

function sensor_module.getInputSensor(index)
    getUbusData()
    local sensorData = ""
    index = tonumber(index)
    local key = sensor_module.hwSensorEnum[index][1]
    if jsonInfo.hwSensors[key] == "0" then
        sensorData = "1"
    elseif jsonInfo.hwSensors[key] == "1" then
        sensorData = "2"
    end
    return sensorData
end

return sensor_module


