---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/12/24 12:16 PM
---
local tf = require "tf_module"

local tf_poe_module = {}

local poePortsEnum = {
    priority    = "priority",
    status      = "status",
    consumption = "consumption"
}

local poeStatusEnum = {
    ["Searching"] = 2,
    ["Delivering power"] = 1
}

local poeEnum = {
    firmware    = "firmware",
    mcu         = "mcu",
    budget      = "budget",
    consumption = "consumption",
    ports       = "ports"
}

local function getPoeStatusInfo()
    local jsonPoeInfo = tf.collectJsonTable("ubus call poe info")
    return jsonPoeInfo
end

function tf_poe_module.getPoeStatus(portNum)
    --local poefile = io.open("/tmp/poePort", "w")
    --poefile:write("getPoeStatus = " .. portNum .. "\n")
    --poefile:close()
    local poeInfoJson = getPoeStatusInfo()
    local portStr = "" .. "lan" .. tostring(portNum)
    --print("ports = " .. tf_poe.poeEnum.ports)

    local poePorts = poeInfoJson[poeEnum.ports]
    local poePortInfo = poePorts[portStr]
    local poePortStatus = poePortInfo[poePortsEnum.status]
    --print("poePortStatus = " .. poePortStatus)
    -- local statusfile = io.open("/tmp/poeStatus", "w")
    -- statusfile:write("getPoeStatus = " .. poePortStatus .. "\n")
    -- statusfile:close()
    local poePortStatusNum = poeStatusEnum[poePortStatus]
    --print("poePortStatusNum = ", poePortStatusNum)
    return poePortStatusNum
end

return tf_poe_module




