
# Copyright (C) 2009 Realtek Semiconductor Corp.
#
# Makefile for SDK Linux Stacking Module
#

MODULE_SRC_PATH     := $(ROOT_PATH)/module/$(MODULE_NAME)/src

STK_PROTOCOL_OBJ := \
	$(MODULE_SRC_PATH)/rlapp.o \
	$(MODULE_SRC_PATH)/rlapp_stack.o

