# Copyright (C) 2020 Realtek Semiconductor Corp.
#
# Makefile for SDK Linux Stacking Module
#

MODULE_SRC_PATH     := $(ROOT_PATH)/module/phyOnlyApp/src

PHYONLYAPP_OBJ := \
	sdk/src/rtk/switch.o \
	sdk/system/linux/usrAppStart.o



