/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009-2016
 * All rights reserved.
 *
 * $Revision$
 * $Date$
 *
 * Purpose : chip table declaration in the SDK.
 *
 * Feature : chip table declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/mango/rtk_mango_table_struct.h>
#include <hal/chipdef/mango/rtk_mango_tableField_list.h>

rtk_table_t rtk_mango_table_list[] =
{
#if defined(CONFIG_SDK_CHIP_FEATURE_802_1Q_VLAN___QINQ)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "VLAN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     3,
        /* table size */            4096,
        /* total data registers */  4,
        /* total field numbers */   MANGO_VLANFIELD_LIST_END,
        /* table fields */          RTL9310_VLAN_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "VLAN_UNTAG",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      3,
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  2,
        /* total field numbers */   MANGO_VLAN_UNTAGFIELD_LIST_END,
        /* table fields */          RTL9310_VLAN_UNTAG_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_802_1Q_VLAN___QINQ */
#if defined(CONFIG_SDK_CHIP_FEATURE_VLAN_TRANSLATION)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "VLAN_EVC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      3,
        /* access table type */     1,
        /* table size */            1024,
        /* total data registers */  6,
        /* total field numbers */   MANGO_VLAN_EVCFIELD_LIST_END,
        /* table fields */          RTL9310_VLAN_EVC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "VLAN_IP_BASED",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     4,
        /* table size */            2048,
        /* total data registers */  6,
        /* total field numbers */   MANGO_VLAN_IP_BASEDFIELD_LIST_END,
        /* table fields */          RTL9310_VLAN_IP_BASED_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "VLAN_IVC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     4,
        /* table size */            2048,
        /* total data registers */  7,
        /* total field numbers */   MANGO_VLAN_IVCFIELD_LIST_END,
        /* table fields */          RTL9310_VLAN_IVC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "VLAN_MAC_BASED",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     4,
        /* table size */            2048,
        /* total data registers */  6,
        /* total field numbers */   MANGO_VLAN_MAC_BASEDFIELD_LIST_END,
        /* table fields */          RTL9310_VLAN_MAC_BASED_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_VLAN_TRANSLATION */
#if defined(CONFIG_SDK_CHIP_FEATURE_LINK_AGGREGATION)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "LAG",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     0,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   MANGO_LAGFIELD_LIST_END,
        /* table fields */          RTL9310_LAG_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "SRC_TRK_MAP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     13,
        /* table size */            1024,
        /* total data registers */  1,
        /* total field numbers */   MANGO_SRC_TRK_MAPFIELD_LIST_END,
        /* table fields */          RTL9310_SRC_TRK_MAP_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_LINK_AGGREGATION */
#if defined(CONFIG_SDK_CHIP_FEATURE_SPANNING_TREE)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "MSTI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     5,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_MSTIFIELD_LIST_END,
        /* table fields */          RTL9310_MSTI_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_SPANNING_TREE */
#if defined(CONFIG_SDK_CHIP_FEATURE_PORT_ISOLATION)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "PORT_ISO_CTRL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     1,
        /* table size */            1024,
        /* total data registers */  2,
        /* total field numbers */   MANGO_PORT_ISO_CTRLFIELD_LIST_END,
        /* table fields */          RTL9310_PORT_ISO_CTRL_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_PORT_ISOLATION */
#if defined(CONFIG_SDK_CHIP_FEATURE_MAC_FORWARDING_CONTROL)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_CAM_CB_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_CAM_CB_MCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_CAM_CB_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_CAM_CB_UC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L2_CAM_CB_UCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_CAM_CB_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_CAM_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L2_CAM_MCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_CAM_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_CAM_UC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L2_CAM_UCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_CAM_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_CB_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_CB_MCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_CB_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_CB_UC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L2_CB_UCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_CB_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L2_MCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_UC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L2_UCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "MC_PMSK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     2,
        /* table size */            4096,
        /* total data registers */  2,
        /* total field numbers */   MANGO_MC_PMSKFIELD_LIST_END,
        /* table fields */          RTL9310_MC_PMSK_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_MAC_FORWARDING_CONTROL */
#if defined(CONFIG_SDK_CHIP_FEATURE_EGRESS_BANDWIDTH_CONTROL)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "EGR_Q_BW",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      4,
        /* access table type */     0,
        /* table size */            56,
        /* total data registers */  29,
        /* total field numbers */   MANGO_EGR_Q_BWFIELD_LIST_END,
        /* table fields */          RTL9310_EGR_Q_BW_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_EGRESS_BANDWIDTH_CONTROL */
#if defined(CONFIG_SDK_CHIP_FEATURE_METER_MARKER)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "METER",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      1,
        /* access table type */     1,
        /* table size */            512,
        /* total data registers */  3,
        /* total field numbers */   MANGO_METERFIELD_LIST_END,
        /* table fields */          RTL9310_METER_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_METER_MARKER */
#if defined(CONFIG_SDK_CHIP_FEATURE_FLOWCONTROL___BACKPRESSURE)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "OUT_Q",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      4,
        /* access table type */     1,
        /* table size */            56,
        /* total data registers */  13,
        /* total field numbers */   MANGO_OUT_QFIELD_LIST_END,
        /* table fields */          RTL9310_OUT_Q_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_FLOWCONTROL___BACKPRESSURE */
#if defined(CONFIG_SDK_CHIP_FEATURE_REMARKING)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "REMARK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      3,
        /* access table type */     4,
        /* table size */            1024,
        /* total data registers */  1,
        /* total field numbers */   MANGO_REMARKFIELD_LIST_END,
        /* table fields */          RTL9310_REMARK_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_REMARKING */
#if defined(CONFIG_SDK_CHIP_FEATURE_LAYER_3_ROUTING)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_ECMP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     5,
        /* table size */            256,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_ECMPFIELD_LIST_END,
        /* table fields */          RTL9310_L3_ECMP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_EGR_INTF",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     8,
        /* table size */            1024,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_EGR_INTFFIELD_LIST_END,
        /* table fields */          RTL9310_L3_EGR_INTF_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_EGR_INTF_CNTR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     13,
        /* table size */            1024,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_EGR_INTF_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_L3_EGR_INTF_CNTR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_EGR_INTF_LIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     9,
        /* table size */            16384,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_EGR_INTF_LISTFIELD_LIST_END,
        /* table fields */          RTL9310_L3_EGR_INTF_LIST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_EGR_TUNNEL_INTF_CNTR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     15,
        /* table size */            384,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_EGR_TUNNEL_INTF_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_L3_EGR_TUNNEL_INTF_CNTR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_HOST_ROUTE_IP6MC_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6MC_0FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6MC_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_HOST_ROUTE_IP6MC_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6MC_1FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6MC_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_HOST_ROUTE_IP6MC_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6MC_2FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6MC_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_HOST_ROUTE_IP6MC_3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6MC_3FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6MC_3_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_HOST_ROUTE_IP6MC_4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6MC_4FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6MC_4_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_HOST_ROUTE_IP6MC_5",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6MC_5FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6MC_5_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_HOST_ROUTE_IP6UC_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6UC_0FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6UC_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_HOST_ROUTE_IP6UC_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6UC_1FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6UC_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_HOST_ROUTE_IP6UC_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6UC_2FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6UC_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_HOST_ROUTE_IPMC_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IPMC_0FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IPMC_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_HOST_ROUTE_IPMC_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IPMC_1FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IPMC_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_HOST_ROUTE_IPUC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IPUCFIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IPUC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_IGR_INTF",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     7,
        /* table size */            1024,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_IGR_INTFFIELD_LIST_END,
        /* table fields */          RTL9310_L3_IGR_INTF_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_IGR_INTF_CNTR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     12,
        /* table size */            1024,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_IGR_INTF_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_L3_IGR_INTF_CNTR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_IGR_TUNNEL_INTF_CNTR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     14,
        /* table size */            384,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_IGR_TUNNEL_INTF_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_L3_IGR_TUNNEL_INTF_CNTR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_NEXTHOP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     6,
        /* table size */            8192,
        /* total data registers */  1,
        /* total field numbers */   MANGO_L3_NEXTHOPFIELD_LIST_END,
        /* table fields */          RTL9310_L3_NEXTHOP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_PREFIX_ROUTE_IP6MC_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6MC_0FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6MC_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_PREFIX_ROUTE_IP6MC_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6MC_1FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6MC_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_PREFIX_ROUTE_IP6MC_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6MC_2FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6MC_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_PREFIX_ROUTE_IP6MC_3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6MC_3FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6MC_3_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_PREFIX_ROUTE_IP6MC_4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6MC_4FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6MC_4_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_PREFIX_ROUTE_IP6MC_5",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6MC_5FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6MC_5_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_PREFIX_ROUTE_IP6UC_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6UC_0FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6UC_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_PREFIX_ROUTE_IP6UC_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6UC_1FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6UC_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_PREFIX_ROUTE_IP6UC_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6UC_2FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6UC_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_PREFIX_ROUTE_IPMC_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IPMC_0FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IPMC_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_PREFIX_ROUTE_IPMC_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IPMC_1FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IPMC_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_PREFIX_ROUTE_IPUC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IPUCFIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IPUC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L3_ROUTER_MAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     2,
        /* table size */            1024,
        /* total data registers */  5,
        /* total field numbers */   MANGO_L3_ROUTER_MACFIELD_LIST_END,
        /* table fields */          RTL9310_L3_ROUTER_MAC_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_LAYER_3_ROUTING */
#if defined(CONFIG_SDK_CHIP_FEATURE_IP_TUNNEL)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "TUNNEL_START",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     9,
        /* table size */            384,
        /* total data registers */  2,
        /* total field numbers */   MANGO_TUNNEL_STARTFIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_START_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "TUNNEL_START_ENCAP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      3,
        /* access table type */     5,
        /* table size */            384,
        /* total data registers */  9,
        /* total field numbers */   MANGO_TUNNEL_START_ENCAPFIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_START_ENCAP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "TUNNEL_START_ENCAP_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      3,
        /* access table type */     5,
        /* table size */            384,
        /* total data registers */  4,
        /* total field numbers */   MANGO_TUNNEL_START_ENCAP_1FIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_START_ENCAP_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "TUNNEL_START_ENCAP_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      3,
        /* access table type */     5,
        /* table size */            384,
        /* total data registers */  4,
        /* total field numbers */   MANGO_TUNNEL_START_ENCAP_2FIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_START_ENCAP_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "TUNNEL_TERMINATION",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     8,
        /* table size */            384,
        /* total data registers */  8,
        /* total field numbers */   MANGO_TUNNEL_TERMINATIONFIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_TERMINATION_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "TUNNEL_TERMINATION_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     8,
        /* table size */            384,
        /* total data registers */  7,
        /* total field numbers */   MANGO_TUNNEL_TERMINATION_1FIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_TERMINATION_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "TUNNEL_TERMINATION_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     8,
        /* table size */            384,
        /* total data registers */  7,
        /* total field numbers */   MANGO_TUNNEL_TERMINATION_2FIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_TERMINATION_2_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_IP_TUNNEL */
#if defined(CONFIG_SDK_CHIP_FEATURE_MPLS_VPLS)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "MPLS_DECAP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     10,
        /* table size */            2048,
        /* total data registers */  4,
        /* total field numbers */   MANGO_MPLS_DECAPFIELD_LIST_END,
        /* table fields */          RTL9310_MPLS_DECAP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "MPLS_DECAP_CAM",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     11,
        /* table size */            64,
        /* total data registers */  4,
        /* total field numbers */   MANGO_MPLS_DECAP_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_MPLS_DECAP_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "MPLS_ENCAP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      3,
        /* access table type */     2,
        /* table size */            2048,
        /* total data registers */  2,
        /* total field numbers */   MANGO_MPLS_ENCAPFIELD_LIST_END,
        /* table fields */          RTL9310_MPLS_ENCAP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "MPLS_NH",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     12,
        /* table size */            8192,
        /* total data registers */  1,
        /* total field numbers */   MANGO_MPLS_NHFIELD_LIST_END,
        /* table fields */          RTL9310_MPLS_NH_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_MPLS_VPLS */
#if defined(CONFIG_SDK_CHIP_FEATURE_MIB_COUNTER)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "STAT_PORT_MIB_CNTR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      5,
        /* access table type */     0,
        /* table size */            57,
        /* total data registers */  53,
        /* total field numbers */   MANGO_STAT_PORT_MIB_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_STAT_PORT_MIB_CNTR_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_MIB_COUNTER */
#if defined(CONFIG_SDK_CHIP_FEATURE_FLOW_BASED_COUNTER)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FLOW_CNTR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      1,
        /* access table type */     2,
        /* table size */            4096,
        /* total data registers */  3,
        /* total field numbers */   MANGO_FLOW_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_FLOW_CNTR_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_FLOW_BASED_COUNTER */
#if defined(CONFIG_SDK_CHIP_FEATURE_PRIVATE_COUNTER)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "AUTO_RECOVERY_TXERR_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      5,
        /* access table type */     2,
        /* table size */            56,
        /* total data registers */  1,
        /* total field numbers */   MANGO_AUTO_RECOVERY_TXERR_CNTFIELD_LIST_END,
        /* table fields */          RTL9310_AUTO_RECOVERY_TXERR_CNT_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "STAT_PORT_PRVTE_CNTR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      5,
        /* access table type */     1,
        /* table size */            57,
        /* total data registers */  28,
        /* total field numbers */   MANGO_STAT_PORT_PRVTE_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_STAT_PORT_PRVTE_CNTR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "STAT_PORT_PRVTE_E_Q_CNTR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     14,
        /* table size */            57,
        /* total data registers */  4,
        /* total field numbers */   MANGO_STAT_PORT_PRVTE_E_Q_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_STAT_PORT_PRVTE_E_Q_CNTR_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_PRIVATE_COUNTER */
#if defined(CONFIG_SDK_CHIP_FEATURE_ACL)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "EACL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      1,
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  22,
        /* total field numbers */   MANGO_EACLFIELD_LIST_END,
        /* table fields */          RTL9310_EACL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "IACL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      1,
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  22,
        /* total field numbers */   MANGO_IACLFIELD_LIST_END,
        /* table fields */          RTL9310_IACL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "VACL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      1,
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  22,
        /* total field numbers */   MANGO_VACLFIELD_LIST_END,
        /* table fields */          RTL9310_VACL_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_ACL */
#if defined(CONFIG_SDK_CHIP_FEATURE_IP_MAC_BIDING)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "IP_MAC_BIND",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     6,
        /* table size */            1024,
        /* total data registers */  4,
        /* total field numbers */   MANGO_IP_MAC_BINDFIELD_LIST_END,
        /* table fields */          RTL9310_IP_MAC_BIND_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "IP_MAC_BIND_CAM",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     7,
        /* table size */            64,
        /* total data registers */  4,
        /* total field numbers */   MANGO_IP_MAC_BIND_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_IP_MAC_BIND_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "IP_MAC_BIND_DYN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     10,
        /* table size */            2048,
        /* total data registers */  4,
        /* total field numbers */   MANGO_IP_MAC_BIND_DYNFIELD_LIST_END,
        /* table fields */          RTL9310_IP_MAC_BIND_DYN_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_IP_MAC_BIDING */
#if defined(CONFIG_SDK_CHIP_FEATURE_OPENFLOW)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "ACTION_BUCKET",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     11,
        /* table size */            8192,
        /* total data registers */  3,
        /* total field numbers */   MANGO_ACTION_BUCKETFIELD_LIST_END,
        /* table fields */          RTL9310_ACTION_BUCKET_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_EGR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      1,
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  17,
        /* total field numbers */   MANGO_FT_EGRFIELD_LIST_END,
        /* table fields */          RTL9310_FT_EGR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_IGR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      1,
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  22,
        /* total field numbers */   MANGO_FT_IGRFIELD_LIST_END,
        /* table fields */          RTL9310_FT_IGR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L2_CAM_FMT0_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_CAM_FMT0_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_CAM_FMT0_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L2_CAM_FMT0_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_CAM_FMT0_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_CAM_FMT0_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L2_CAM_FMT1_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_CAM_FMT1_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_CAM_FMT1_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L2_CAM_FMT1_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_CAM_FMT1_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_CAM_FMT1_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L2_CAM_FMT2_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_CAM_FMT2_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_CAM_FMT2_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L2_HASH_FMT0_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_HASH_FMT0_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_HASH_FMT0_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L2_HASH_FMT0_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_HASH_FMT0_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_HASH_FMT0_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L2_HASH_FMT1_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_HASH_FMT1_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_HASH_FMT1_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L2_HASH_FMT1_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_HASH_FMT1_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_HASH_FMT1_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L2_HASH_FMT2_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_HASH_FMT2_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_HASH_FMT2_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L2_HASH_FMT2_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_HASH_FMT2_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_HASH_FMT2_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L3_HASH_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L3_HASH_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L3_HASH_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L3_HASH_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L3_HASH_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L3_HASH_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L3_HASH_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L3_HASH_2FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L3_HASH_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L3_TCAM_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_FT_L3_TCAM_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L3_TCAM_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L3_TCAM_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_FT_L3_TCAM_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L3_TCAM_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "FT_L3_TCAM_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_FT_L3_TCAM_2FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L3_TCAM_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "GROUP_TBL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      2,
        /* access table type */     10,
        /* table size */            2048,
        /* total data registers */  1,
        /* total field numbers */   MANGO_GROUP_TBLFIELD_LIST_END,
        /* table fields */          RTL9310_GROUP_TBL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "OF_DMAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     15,
        /* table size */            1024,
        /* total data registers */  2,
        /* total field numbers */   MANGO_OF_DMACFIELD_LIST_END,
        /* table fields */          RTL9310_OF_DMAC_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_OPENFLOW */
#if defined(CONFIG_SDK_CHIP_FEATURE_L2_TUNNEL)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "BSSID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     10,
        /* table size */            2048,
        /* total data registers */  3,
        /* total field numbers */   MANGO_BSSIDFIELD_LIST_END,
        /* table fields */          RTL9310_BSSID_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "BSSID_CAM",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     11,
        /* table size */            64,
        /* total data registers */  4,
        /* total field numbers */   MANGO_BSSID_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_BSSID_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "BSSID_LIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     12,
        /* table size */            8192,
        /* total data registers */  1,
        /* total field numbers */   MANGO_BSSID_LISTFIELD_LIST_END,
        /* table fields */          RTL9310_BSSID_LIST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "BSSID_TUNNEL_START",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      3,
        /* access table type */     3,
        /* table size */            2048,
        /* total data registers */  4,
        /* total field numbers */   MANGO_BSSID_TUNNEL_STARTFIELD_LIST_END,
        /* table fields */          RTL9310_BSSID_TUNNEL_START_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "CAPWAP_TUNNEL_START_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     9,
        /* table size */            384,
        /* total data registers */  9,
        /* total field numbers */   MANGO_CAPWAP_TUNNEL_START_0FIELD_LIST_END,
        /* table fields */          RTL9310_CAPWAP_TUNNEL_START_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "CAPWAP_TUNNEL_START_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     9,
        /* table size */            384,
        /* total data registers */  4,
        /* total field numbers */   MANGO_CAPWAP_TUNNEL_START_1FIELD_LIST_END,
        /* table fields */          RTL9310_CAPWAP_TUNNEL_START_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_TNL_LST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     12,
        /* table size */            8192,
        /* total data registers */  1,
        /* total field numbers */   MANGO_L2_TNL_LSTFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_LST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_TNL_MCAST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_TNL_MCASTFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_MCAST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_TNL_MCAST_CAM",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_TNL_MCAST_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_MCAST_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_TNL_UCAST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_TNL_UCASTFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_UCAST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_TNL_UCAST_CAM",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_TNL_UCAST_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_UCAST_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_TNL_VXLAN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     10,
        /* table size */            2048,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_TNL_VXLANFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_VXLAN_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_TNL_VXLAN_CAM",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     11,
        /* table size */            64,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_TNL_VXLAN_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_VXLAN_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_TNL_VXLAN_ENCAP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      3,
        /* access table type */     3,
        /* table size */            2112,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L2_TNL_VXLAN_ENCAPFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_VXLAN_ENCAP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "VXLAN_TUNNEL_START_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     9,
        /* table size */            384,
        /* total data registers */  9,
        /* total field numbers */   MANGO_VXLAN_TUNNEL_START_0FIELD_LIST_END,
        /* table fields */          RTL9310_VXLAN_TUNNEL_START_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "VXLAN_TUNNEL_START_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     9,
        /* table size */            384,
        /* total data registers */  4,
        /* total field numbers */   MANGO_VXLAN_TUNNEL_START_1FIELD_LIST_END,
        /* table fields */          RTL9310_VXLAN_TUNNEL_START_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "WLC_MCAST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  3,
        /* total field numbers */   MANGO_WLC_MCASTFIELD_LIST_END,
        /* table fields */          RTL9310_WLC_MCAST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "WLC_MCAST_CAM",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   MANGO_WLC_MCAST_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_WLC_MCAST_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "WLC_UCAST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  3,
        /* total field numbers */   MANGO_WLC_UCASTFIELD_LIST_END,
        /* table fields */          RTL9310_WLC_UCAST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "WLC_UCAST_CAM",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   MANGO_WLC_UCAST_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_WLC_UCAST_CAM_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_L2_TUNNEL */
#if defined(CONFIG_SDK_CHIP_FEATURE_PORT_EXTENSION)
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "ECID_PMSK_LIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     12,
        /* table size */            8192,
        /* total data registers */  2,
        /* total field numbers */   MANGO_ECID_PMSK_LISTFIELD_LIST_END,
        /* table fields */          RTL9310_ECID_PMSK_LIST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "ECID_PVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     10,
        /* table size */            2048,
        /* total data registers */  2,
        /* total field numbers */   MANGO_ECID_PVIDFIELD_LIST_END,
        /* table fields */          RTL9310_ECID_PVID_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "ECID_PVID_CAM",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     11,
        /* table size */            64,
        /* total data registers */  2,
        /* total field numbers */   MANGO_ECID_PVID_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_ECID_PVID_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "PE_FWD",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_PE_FWDFIELD_LIST_END,
        /* table fields */          RTL9310_PE_FWD_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "PE_FWD_CAM",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_PE_FWD_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_PE_FWD_CAM_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_PORT_EXTENSION */
};

