#
# Copyright (C) 2009 Realtek Semiconductor Corp.
#
# Makefile for SDK Unit Test Directory
#

DAL_OBJ := \
	dal_vlan_test_case.o \
	dal_qos_test_case.o \
	dal_eee_test_case.o \
	dal_flowctrl_test_case.o \
	dal_rate_test_case.o \
	dal_l2_test_case.o \
	dal_trunk_test_case.o \
	dal_switch_test_case.o \
	dal_stp_test_case.o \
	dal_trap_test_case.o \
	dal_port_test_case.o \
	dal_stat_test_case.o \
	dal_mirror_test_case.o \
	dal_mpls_test_case.o \
	dal_time_test_case.o \
	dal_led_test_case.o \
	dal_acl_test_case.o \
	dal_l3_test_case.o \
	dal_sec_test_case.o \
	dal_oam_test_case.o

