#!/usr/bin/lua

---
--- Generated by Luanalysis
--- Created by sheverdin.
--- DateTime: 2/16/24 4:33 PM
---

local tf            = require "tf_module"
local igmp          = require "igmp_module"
local igmpStatus    = require "igmp_status"

local portRange = {}

local show_igmp_option =
{
    "status",
    "config"
}

function  igmp_show_status ()
    io.write("igmp_show_status ... \n")
    local dev_mcast = tf.executeCommand("cat /proc/net/dev_mcast")
    --print(dev_mcast)
    igmpStatus.main_show_igmp_status(portRange)
end

function igmp_show_config ()
    io.write("IGMP snoping config: \n")
    for i, option in pairs(igmp.option) do
        local ubusStr = tf.ubusList.cmd_ubus ..
                tf.ubusList.cmd_get ..
                tf.ubusList.cmd_prefix ..
                tf.ubusList.cmd_config .. "network" ..
                tf.ubusList.cmd_section .. "switch" ..
                tf.ubusList.cmd_option .. option ..
                tf.ubusList.cmd_suffix
        local switchData = tf.collectJsonTable(ubusStr)
        if (switchData == nil) then
            io.write(igmp.printStr[i], "not configured\n")
        else
            io.write(igmp.printStr[i], switchData["value"], "\n")
        end
    end
end

local igmp_show_cmdList = {
    { cmd = "status", func = igmp_show_status},
    { cmd = "config", func = igmp_show_config},
}

function show_igmp(cmdList)
    local error = 1
    for _, value in pairs(cmdList) do
        if arg[1] == value.cmd then
            error = value.func()
        end
    end
end

function main_show_igmp()
    local errorCode = tf.validateParam(2, arg)
    if errorCode == 0 then
        portRange = tf.checkPortRange(arg[2])
        if (portRange ~= nil) then
            show_igmp(igmp_show_cmdList)
        end
    end
end

main_show_igmp()