#!/usr/bin/lua

---
--- Generated by Luanalysis
--- Created by sheverdin.
--- DateTime: 2/26/24 10:55 AM
---

--print("---------------- get network ver 1.4 ----------")

local tf = require "tf_module"

function main_getNetInfo()
    local cmd_getDeviceInfo  = ""
    cmd_getDeviceInfo = tf.ubusList.cmd_ubus ..  tf.ubusList.cmd_get ..  tf.ubusList.cmd_prefix .. tf.ubusList.cmd_config ..
            "network" .. tf.ubusList.cmd_section .. "lan" .. tf.ubusList.cmd_option .. "device" .. tf.ubusList.cmd_suffix
    --print(cmd_getDeviceInfo)

    local jsonData = tf.collectJsonTable(cmd_getDeviceInfo)
    if #jsonData.value > 0 then
        print(jsonData.value)
    else
        print("")
    end

end

main_getNetInfo()





