#!/usr/bin/lua

---
--- Generated by Luanalysis
--- Created by sheverdin.
--- DateTime: 2/26/24 2:25 PM
---

--print("---------------- get model ver 1.3 ----------")

local tf = require "tf_module"

local system_board =
{
    kernel     = "kernel",
    hostname   = "hostname",
    system     = "system",
    board_name = "board_name",
    rootfs_type = "rootfs_type",
    release     = "release"
}

local release_t  = {
    distribution = "distribution",
    version = "version",
    revision = "revision",
    target = "target",
    description = "description"
}

local modelTable =
{
    "PSW-2G",
    "PSW-2G-UPS",
    "PSW-2G+",
    "PSW-1G4F",
    "PSW-2G4F",
    "PSW-2G6F+",
    "psw-2g8f",
    "PSW-1G4F-UPS",
    "PSW-2G4F-UPS",
    "PSW-2G+UPS-Box"
};

function getModelType(input_string)
    local parts = {}
    local model = ""
    local index = 0
    for part in input_string:gmatch("[^,]+") do
        table.insert(parts, part)
    end

    if #parts == 2 then
        model = parts[2]
        for i, model_value in pairs(modelTable) do
            if model == model_value then
               index = i
            end
        end
        --print("Second part: " .. model)
    else
        index = 0
        --print("ERROR: Input string is wrong format")
    end
    print(index)
end

function main_getModel()
    local cmd_getModelInfo  = ""
    local model = ""
    cmd_getModelInfo = "ubus call system board"
    local jsonData = tf.collectJsonTable(cmd_getModelInfo)
    getModelType(jsonData[system_board.board_name])
end

main_getModel()


