#!/usr/bin/lua

---
--- Generated by Luanalysis
--- Created by sheverdin.
--- DateTime: 2/28/24 3:07 PM
---

local tf = require "tf_module"

local netParam = {
    macaddr = "macaddr",
    ipaddr  = "ipaddr",
    netmask = "netmask",
    gateway = "ip r"
}

function getIp(value)
    for part in value:gmatch("(%d+)") do
        print(part)
    end

end

function getMAC(value)
    for part in value:gmatch("(%d+)") do
        print(part)
    end
end

function getMask(value)
    for part in value:gmatch("(%d+)") do
        print(part)
    end
end

function getGateWay()
    local ipTable = tf.executeCommand("ip r")
    for part in ipTable:gmatch("(%d+)") do
        print(part)
    end
end

function main_getNetInfo()

    if (arg[1] == "gateWay") then
        getGateWay()
    else
        local getNetInfo = ""
        local getNetInfo = tf.ubusList.cmd_ubus ..  tf.ubusList.cmd_get ..  tf.ubusList.cmd_prefix .. tf.ubusList.cmd_config ..
                "network" .. tf.ubusList.cmd_section .. arg[2] .. tf.ubusList.cmd_suffix
        local jsonData = tf.collectJsonTable(getNetInfo)
        if type(jsonData.values) == "table" then
            if arg[1] == netParam.ipaddr        then
                getIp(jsonData.values[arg[1]])
            elseif arg[1] == netParam.macaddr   then
                getMAC(jsonData.values[arg[1]])
            elseif arg[1] == netParam.netmask   then
                getIp(jsonData.values[arg[1]])
            end
        else
            print("")
        end
    end
end

main_getNetInfo()
