#!/usr/bin/lua

---
--- Generated by Luanalysis
--- Created by sheverdin.
--- DateTime: 2/26/24 10:55 AM
---

--print("---------------- get network ver 1.4 ----------")

local tf = require "tf_module"

local sysDevParam = {
    if_name = "if_name",
    dev_name = "dev_name"
}

function main_getNetDeviceInfo()

    getDeviceInfo  = ""
    cmd_getDeviceInfo = tf.ubusList.cmd_ubus ..  tf.ubusList.cmd_get ..  tf.ubusList.cmd_prefix .. tf.ubusList.cmd_config ..
            "tf_device_monitor" .. tf.ubusList.cmd_section .. "sysDevName" .. tf.ubusList.cmd_suffix
    --print(cmd_getDeviceInfo)

    local jsonData = tf.collectJsonTable(cmd_getDeviceInfo)
    if type(jsonData.values) == "table" then
        for k,value in pairs(jsonData.values[arg[1]]) do
            print(value)
        end
    else
        print("")
    end

end

main_getNetDeviceInfo()





