#!/usr/bin/lua

---
--- Generated by Luanalysis
--- Created by sheverdin.
--- DateTime: 3/1/24 10:51 AM
---

local tf = require "tf_module"

local timeInfo = {
    localtime   = "localtime",
    uptime      = "uptime"
}

function main_getTimeInfo()
    local  cmd_getTimeInfo = "ubus call system info"
    --print(cmd_getDeviceInfo)

    local jsonData = tf.collectJsonTable(cmd_getTimeInfo)
    if type(jsonData) == "table" then
        local uptime = jsonData[timeInfo.uptime]
        print(uptime)
    else
        print("")
    end
end

main_getTimeInfo()