
# Copyright (C) 2009 Realtek Semiconductor Corp.
#
# Makefile for SDK Linux Stacking Module
#

MODULE_SRC_PATH     := $(ROOT_PATH)/module/$(MODULE_NAME)/src

RTSDN_OBJ := \
	$(MODULE_SRC_PATH)/rtk_sdn_task.o \
	$(MODULE_SRC_PATH)/rtk_sdn.o \
	$(MODULE_SRC_PATH)/rtk_dpa.o \
	$(MODULE_SRC_PATH)/rtk_gtp_fpga.o \
	$(MODULE_SRC_PATH)/sdn_db.o \
	$(MODULE_SRC_PATH)/sdn_hal/RTK931X/sdn_hal.o \
	$(MODULE_SRC_PATH)/sdn_hal/RTK931X/sdn_util.o

