/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009-2016
 * All rights reserved.
 *
 * $Revision$
 * $Date$
 *
 * Purpose : chip table field declaration in the SDK.
 *
 * Feature : chip table field declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/cypress/rtk_cypress_table_struct.h>

#if defined(CONFIG_SDK_CHIP_FEATURE_ADDRESS_TABLE_LOOKUP)
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_CAM_IP_MC_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   84,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ZERO",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "GIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   31,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MC_PMSK_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   6,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_CAM_IP_MC_SIP_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "GIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   31,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   18,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MC_PMSK_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   6,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_CAM_MC_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   84,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   36,
        /* len */   48,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   31,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MC_PMSK_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   6,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_CAM_UC_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   84,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   36,
        /* len */   48,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   31,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SLP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   24,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AGE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   21,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SA_BLK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   20,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "DA_BLK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   19,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATIC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   18,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SUSPEND",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   17,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEXT_HOP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   16,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   4,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_IP_MC_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   84,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ZERO",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "GIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   31,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MC_PMSK_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   6,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_IP_MC_SIP_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "GIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   31,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   18,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MC_PMSK_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   6,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_MC_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   84,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   36,
        /* len */   48,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   31,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MC_PMSK_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   6,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_NEXT_HOP_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   84,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   36,
        /* len */   48,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "RSVD",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   4,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   31,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SLP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   24,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AGE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   21,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SA_BLK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   20,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "DA_BLK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   19,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATIC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   18,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SUSPEND",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   17,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEXT_HOP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   16,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VLAN_TARGET",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   15,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ROUTE_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   4,
        /* len */   11,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_NH_LEGACY_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "HOSTMAC_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   45,
        /* len */   11,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   44,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "DVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "DPA",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   24,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEXT_HOP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   16,
        /* len */   1,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_L2_UC_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_RVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   84,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   36,
        /* len */   48,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "RSVD",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   4,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   31,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IP6_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SLP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   24,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AGE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   21,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SA_BLK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   20,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "DA_BLK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   19,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATIC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   18,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SUSPEND",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   17,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEXT_HOP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   16,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   4,
        /* len */   12,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_MC_PMSK_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PMSK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   11,
        /* len */   53,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_ADDRESS_TABLE_LOOKUP */
#if defined(CONFIG_SDK_CHIP_FEATURE__IEEE802_1Q__VLAN)
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_UNTAG_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PMSK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   11,
        /* len */   53,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_VLAN_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MBR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   43,
        /* len */   53,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FID_MSTI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   35,
        /* len */   8,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "L2_HASH_KEY_UC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   34,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "L2_HASH_KEY_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   33,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VLAN_PROFILE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   3,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_VLAN_EGR_CNVT_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VALID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   127,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ORG_VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   115,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ORG_VID_RNG_CHK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   83,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ORG_PRI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   80,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PORT_ID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   74,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_VALID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   73,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ORG_VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   61,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ORG_VID_RNG_CHK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   29,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ORG_PRI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   26,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_PORT_ID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   20,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID_SHIFT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   19,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEW_VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   7,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PRI_ASSIGN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   6,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEW_PRI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   3,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TPID_ASSIGN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   2,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TPID_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_VLAN_IGR_CNVT_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VALID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   159,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   147,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IVID_RNG_CHK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   115,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IPRI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   112,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PORTID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   105,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_VALID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   104,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_IVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   92,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_IVID_RNG_CHK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   60,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_IPRI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   57,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_RESERVED",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   56,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_PORTID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   50,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   49,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID_SHIFT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   48,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEW_VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   36,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PRI_ASSIGN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   35,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEW_PRI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ITAG_STS",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OTAG_STS",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   28,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TPID_ASSIGN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   27,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TPID_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   25,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_VLAN_IP_SUBNET_BASED_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VALID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   159,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   127,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PORTID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   105,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_VALID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   104,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_SIP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   72,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_PORTID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   50,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   49,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID_SHIFT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   48,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEW_VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   36,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PRI_ASSIGN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   35,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEW_PRI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ITAG_STS",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OTAG_STS",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   28,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TPID_ASSIGN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   27,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TPID_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   25,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_VLAN_MAC_BASED_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VALID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   159,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SMAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   111,
        /* len */   48,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PORTID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   105,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_VALID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   104,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_SMAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   56,
        /* len */   48,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_PORTID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   50,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID_SEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   49,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VID_SHIFT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   48,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEW_VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   36,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PRI_ASSIGN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   35,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NEW_PRI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ITAG_STS",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OTAG_STS",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   28,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TPID_ASSIGN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   27,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TPID_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   25,
        /* len */   2,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE__IEEE802_1Q__VLAN */
#if defined(CONFIG_SDK_CHIP_FEATURE_SPANNING_TREE)
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_MSTI_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT51",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   126,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT50",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   124,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT49",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   122,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT48",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   120,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT47",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   118,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT46",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   116,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT45",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   114,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT44",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   112,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT43",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   110,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT42",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   108,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT41",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   106,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT40",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   104,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT39",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   102,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT38",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   100,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT37",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   98,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT36",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   96,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT35",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   94,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT34",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   92,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT33",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   90,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT32",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   88,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT31",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   86,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT30",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   84,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT29",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   82,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT28",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   80,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT27",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   78,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT26",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   76,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT25",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   74,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT24",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   72,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT23",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   70,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT22",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   68,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT21",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   66,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT20",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT19",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   62,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT18",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   60,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT17",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   58,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT16",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   56,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT15",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   54,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT14",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   52,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT13",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   50,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT12",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   48,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT11",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   46,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT10",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   44,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT9",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   42,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT8",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   40,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT7",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   38,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT6",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   36,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT5",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   34,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   32,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   30,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   28,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   26,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STATE_PORT0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   24,
        /* len */   2,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_SPANNING_TREE */
#if defined(CONFIG_SDK_CHIP_FEATURE_METER_MARKER)
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_METER_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TYPE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   62,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "COLOR_AWARE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   61,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LB0_RATE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   41,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LB1_RATE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   21,
        /* len */   20,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_METER_MARKER */
#if defined(CONFIG_SDK_CHIP_FEATURE_STATISTIC_COUNTERS)
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_LOG_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "CNTR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   0,
        /* len */   64,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_STATISTIC_COUNTERS */
#if defined(CONFIG_SDK_CHIP_FEATURE_FLOWCONTROL___BACKPRESSURE_THRESHOLD)
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_OUT_Q_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q0_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   244,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q0_MAX_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   232,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q1_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   220,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q1_MAX_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   208,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q2_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   196,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q2_MAX_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   184,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q3_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   172,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q3_MAX_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   160,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q4_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   148,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q4_MAX_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   136,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q5_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   124,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q5_MAX_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   112,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q6_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   100,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q6_MAX_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   88,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q7_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   76,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "Q7_MAX_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   64,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PE_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   52,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PE_MAX_USED_PAGE_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   40,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "P_EGR_DROP_ON_THR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   28,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "P_EGR_DROP_OFF_THR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   16,
        /* len */   12,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_FLOWCONTROL___BACKPRESSURE_THRESHOLD */
#if defined(CONFIG_SDK_CHIP_FEATURE_SCHEDULING)
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_SCHED_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LB_APR_Q7",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   268,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LB_APR_Q6",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   248,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LB_APR_Q5",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   228,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LB_APR_Q4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   208,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LB_APR_Q3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   188,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LB_APR_Q2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   168,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LB_APR_Q1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   148,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LB_APR_Q0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   128,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "WEIGHT_Q7",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   118,
        /* len */   10,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "WEIGHT_Q6",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   108,
        /* len */   10,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "WEIGHT_Q5",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   98,
        /* len */   10,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "WEIGHT_Q4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   88,
        /* len */   10,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "WEIGHT_Q3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   78,
        /* len */   10,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "WEIGHT_Q2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   68,
        /* len */   10,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "WEIGHT_Q1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   58,
        /* len */   10,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "WEIGHT_Q0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   48,
        /* len */   10,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIX_TKN_Q7",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   47,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIX_TKN_Q6",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   46,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIX_TKN_Q5",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   45,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIX_TKN_Q4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   44,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIX_TKN_Q3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   43,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIX_TKN_Q2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   42,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIX_TKN_Q1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   41,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIX_TKN_Q0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   40,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "EGR_RATE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   20,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SCHED_TYPE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   19,
        /* len */   1,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_SCHEDULING */
#if defined(CONFIG_SDK_CHIP_FEATURE_INGRESS_AND_EGRESS_ACL)
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_EACL_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_11",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   528,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_10",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   512,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_9",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   496,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_8",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   480,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_7",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   464,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_6",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   448,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_5",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   432,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   416,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   400,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   384,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   368,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   352,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SPMMASK_FIX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   350,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SPN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   344,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MGNT_VLAN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   343,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SWITCHMAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   342,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NOT_FIRST_FRAG",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   341,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FRAME_TYPE_L4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   338,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FRAME_TYPE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   336,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OTAG_FMT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   335,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ITAG_FMT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   334,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OTAG_EXIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   333,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ITAG_EXIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   332,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FRAME_TYPE_L2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   330,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   328,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_11",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   312,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_10",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   296,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_9",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   280,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_8",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   264,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_7",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   248,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_6",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   232,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_5",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   216,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   200,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   184,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   168,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   152,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   136,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_SPMMASK_FIX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   134,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_SPN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   128,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_MGNT_VLAN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   127,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_SWITCHMAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   126,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_NOT_FIRST_FRAG",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   125,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FRAME_TYPE_L4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   122,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FRAME_TYPE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   120,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_OTAG_FMT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   119,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ITAG_FMT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   118,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_OTAG_EXIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   117,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ITAG_EXIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   116,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FRAME_TYPE_L2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   114,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_TID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   112,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VALID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   111,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NOT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   110,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AND1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   109,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AND2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   108,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_TAG_STS",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   107,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_QOS_REMARK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   106,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_PRI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   105,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_OVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   104,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_IVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   103,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_METER",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   102,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_MIRROR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   101,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_LOG",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   100,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_FWD",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   99,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FWD_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   96,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FWD_PORT_INFO",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   82,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LOG_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   81,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LOG_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   70,
        /* len */   11,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MIR_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   69,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MIR_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   67,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "METER_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   58,
        /* len */   9,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IVLAN_TPID_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   57,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IVLAN_VID_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   55,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IVLAN_TPID_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   53,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IVLAN_VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   41,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OVLAN_TPID_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   40,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OVLAN_VID_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   38,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OVLAN_TPID_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   36,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OVLAN_VID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   24,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PRI_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   23,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "INT_PRI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   20,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "RMK_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   16,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "RMK_VAL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   10,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TAG_STS_OUTER",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   8,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TAG_STS_INNER",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   6,
        /* len */   2,
    },
};
#endif
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_IACL_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_11",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   528,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_10",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   512,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_9",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   496,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_8",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   480,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_7",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   464,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_6",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   448,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_5",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   432,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   416,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   400,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   384,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   368,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FIELD_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   352,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SPMMASK_FIX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   350,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SPN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   344,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MGNT_VLAN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   343,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SWITCHMAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   342,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NOT_FIRST_FRAG",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   341,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FRAME_TYPE_L4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   338,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FRAME_TYPE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   336,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OTAG_FMT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   335,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ITAG_FMT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   334,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OTAG_EXIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   333,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ITAG_EXIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   332,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FRAME_TYPE_L2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   330,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "TID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   328,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_11",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   312,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_10",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   296,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_9",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   280,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_8",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   264,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_7",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   248,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_6",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   232,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_5",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   216,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   200,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_3",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   184,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   168,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   152,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FIELD_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   136,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_SPMMASK_FIX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   134,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_SPN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   128,
        /* len */   6,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_MGNT_VLAN",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   127,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_SWITCHMAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   126,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_NOT_FIRST_FRAG",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   125,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FRAME_TYPE_L4",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   122,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FRAME_TYPE",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   120,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_OTAG_FMT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   119,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ITAG_FMT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   118,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_OTAG_EXIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   117,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_ITAG_EXIST",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   116,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_FRAME_TYPE_L2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   114,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BMSK_TID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   112,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "VALID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   111,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "NOT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   110,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AND1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   109,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "AND2",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   108,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_BYPASS",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   107,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_MPLS",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   106,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_PRI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   105,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_OVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   104,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_IVID",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   103,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_METER",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   102,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_MIRROR",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   101,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_LOG",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   100,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "ACT_MSK_FWD",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   99,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FWD_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   96,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "FWD_PORT_INFO",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   82,
        /* len */   14,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LOG_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   81,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "LOG_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   70,
        /* len */   11,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MIR_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   67,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "METER_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   58,
        /* len */   9,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IVLAN_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   55,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "IVLAN_DATA",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   41,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OVLAN_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   38,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "OVLAN_DATA",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   24,
        /* len */   12,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "INT_PRI",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   20,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MPLS_ACT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   19,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "MPLS_LIB_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   10,
        /* len */   9,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BYPASS_ALL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   9,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BYPASS_IGR_STP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   8,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BYPASS_IBC_SC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   7,
        /* len */   1,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_INGRESS_AND_EGRESS_ACL */
#if defined(CONFIG_SDK_CHIP_FEATURE_SMART_PACKET_GENERATOR)
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_SPG_PORT_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "PKT_CNT",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   192,
        /* len */   32,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BAD_CRC_EN_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   191,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_LEN_TYPE_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   189,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_RNDM_OFFSET_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   184,
        /* len */   5,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_RNDM_EN_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   183,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_SA_INC_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   182,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_DA_INC_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   181,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_PKT_CNT_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   165,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_LEN_RNG_START_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   151,
        /* len */   14,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_LEN_RNG_END_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   137,
        /* len */   14,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_DA_REPEAT_CNT_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   122,
        /* len */   15,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_SA_REPEAT_CNT_0",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   107,
        /* len */   15,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "BAD_CRC_EN_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   106,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_LEN_TYPE_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   104,
        /* len */   2,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_RNDM_OFFSET_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   99,
        /* len */   5,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_RNDM_EN_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   98,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_SA_INC_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   97,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_DA_INC_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   96,
        /* len */   1,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_PKT_CNT_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   80,
        /* len */   16,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_LEN_RNG_START_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   66,
        /* len */   14,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_LEN_RNG_END_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   52,
        /* len */   14,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_DA_REPEAT_CNT_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   37,
        /* len */   15,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "STREAM_SA_REPEAT_CNT_1",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   22,
        /* len */   15,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_SMART_PACKET_GENERATOR */
#if defined(CONFIG_SDK_CHIP_FEATURE_L3_ROUTING)
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_ROUTING_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "GATEWAY_MAC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   16,
        /* len */   48,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "SW_MAC_IDX",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   12,
        /* len */   4,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_L3_ROUTING */
#if defined(CONFIG_SDK_CHIP_FEATURE_L3_VPN_MPLS)
#if defined(CONFIG_SDK_RTL8390)
rtk_tableField_t RTL8390_MPLS_LIB_FIELDS[] =
{
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "I_LABEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   44,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "I_EXP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   41,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "I_TTL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   33,
        /* len */   8,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "O_LABEL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   13,
        /* len */   20,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "O_EXP",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   10,
        /* len */   3,
    },
    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* name */  "O_TTL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* lsp */   2,
        /* len */   8,
    },
};
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_L3_VPN_MPLS */

