---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/12/24 10:55 AM
---

utils = {}

function utils.countDots(str)
    local count = 0
    for char in str:gmatch(".") do
        if char == '.' then
            count = count + 1
        end
    end
    return count
end

function utils.separateLettersAndNumbers(inputString)
    local letters = ""
    local numbers = ""
    for i = 1, #inputString do
        local char = inputString:sub(i, i)
        if tonumber(char) ~= nil then
            numbers = numbers .. char
        else
            letters = letters .. char
        end
    end
    return letters, tonumber(numbers)
end

return utils